<?php

return [

    'permissions' => [
        ['key' => 'kyc_applications', 'name' => 'KYC applications', 'group' => 'Onboarding'],
        ['key' => 'agent_records', 'name' => 'Agent records', 'group' => 'Onboarding'],
        ['key' => 'transactions', 'name' => 'Transactions', 'group' => 'Operations'],
        ['key' => 'reversals', 'name' => 'Reversals', 'group' => 'Operations'],
        ['key' => 'aml_cases', 'name' => 'AML cases', 'group' => 'Risk'],
        ['key' => 'str_filings', 'name' => 'STR filings', 'group' => 'Risk'],
        ['key' => 'sanctions_screening', 'name' => 'Sanctions screening', 'group' => 'Risk'],
        ['key' => 'settlement_recon', 'name' => 'Settlement & recon', 'group' => 'Finance'],
        ['key' => 'float_positions', 'name' => 'Float positions', 'group' => 'Finance'],
        ['key' => 'fee_schedules', 'name' => 'Fee schedules', 'group' => 'Finance'],
        ['key' => 'commission_payout', 'name' => 'Commission payout', 'group' => 'Finance'],
        ['key' => 'regulatory_filings', 'name' => 'Regulatory filings', 'group' => 'Compliance'],
        ['key' => 'audit_logs', 'name' => 'Audit logs', 'group' => 'Governance'],
        ['key' => 'user_management', 'name' => 'User & role management', 'group' => 'Governance'],
        ['key' => 'system_config', 'name' => 'System configuration', 'group' => 'Governance'],
    ],

    /** Default permission matrix per system role slug */
    'role_matrix' => [
        'super_admin' => [
            'kyc_applications' => 'write',
            'agent_records' => 'read',
            'transactions' => 'read',
            'reversals' => 'read',
            'aml_cases' => 'read',
            'str_filings' => 'read',
            'sanctions_screening' => 'read',
            'settlement_recon' => 'read',
            'float_positions' => 'write',
            'fee_schedules' => 'write',
            'commission_payout' => 'write',
            'regulatory_filings' => 'read',
            'audit_logs' => 'append',
            'user_management' => 'write',
            'system_config' => 'write',
        ],
        'kyc_officer' => [
            'kyc_applications' => 'write',
            'agent_records' => 'read',
            'sanctions_screening' => 'read',
        ],
        'agent_manager' => [
            'kyc_applications' => 'write',
            'agent_records' => 'write',
            'transactions' => 'read',
            'float_positions' => 'read',
            'fee_schedules' => 'read',
            'commission_payout' => 'read',
            'sanctions_screening' => 'read',
        ],
        'operations_lead' => [
            'kyc_applications' => 'read',
            'agent_records' => 'read',
            'transactions' => 'read',
            'reversals' => 'read',
            'aml_cases' => 'read',
            'settlement_recon' => 'read',
            'float_positions' => 'read',
            'fee_schedules' => 'read',
            'regulatory_filings' => 'read',
            'audit_logs' => 'read',
            'system_config' => 'read',
        ],
        'customer_support' => [
            'kyc_applications' => 'read',
            'agent_records' => 'read',
            'transactions' => 'read',
            'reversals' => 'write',
            'sanctions_screening' => 'read',
        ],
        'aml_analyst' => [
            'agent_records' => 'read',
            'transactions' => 'read',
            'reversals' => 'read',
            'aml_cases' => 'write',
            'str_filings' => 'write',
            'sanctions_screening' => 'write',
            'audit_logs' => 'read',
        ],
        'compliance_officer' => [
            'kyc_applications' => 'write',
            'agent_records' => 'read',
            'transactions' => 'read',
            'reversals' => 'read',
            'aml_cases' => 'read',
            'str_filings' => 'write',
            'sanctions_screening' => 'read',
            'settlement_recon' => 'read',
            'float_positions' => 'read',
            'fee_schedules' => 'read',
            'commission_payout' => 'read',
            'regulatory_filings' => 'write',
            'audit_logs' => 'read',
            'system_config' => 'read',
        ],
        'settlement_officer' => [
            'agent_records' => 'read',
            'transactions' => 'read',
            'reversals' => 'write',
            'settlement_recon' => 'write',
            'float_positions' => 'read',
            'fee_schedules' => 'read',
            'commission_payout' => 'read',
            'regulatory_filings' => 'read',
            'audit_logs' => 'read',
            'system_config' => 'read',
        ],
        'finance_treasury' => [
            'agent_records' => 'read',
            'transactions' => 'read',
            'reversals' => 'write',
            'settlement_recon' => 'read',
            'float_positions' => 'write',
            'fee_schedules' => 'write',
            'commission_payout' => 'write',
            'regulatory_filings' => 'read',
            'audit_logs' => 'read',
            'system_config' => 'read',
        ],
    ],

    'roles' => [
        ['slug' => 'super_admin', 'name' => 'Super Admin', 'department' => 'Governance', 'is_system' => true],
        ['slug' => 'kyc_officer', 'name' => 'KYC Officer', 'department' => 'Onboarding', 'is_system' => true],
        ['slug' => 'agent_manager', 'name' => 'Agent Manager', 'department' => 'Onboarding', 'is_system' => true],
        ['slug' => 'operations_lead', 'name' => 'Operations Lead', 'department' => 'Operations', 'is_system' => true],
        ['slug' => 'customer_support', 'name' => 'Customer Support', 'department' => 'Operations', 'is_system' => true],
        ['slug' => 'aml_analyst', 'name' => 'AML Analyst', 'department' => 'Risk & Control', 'is_system' => true],
        ['slug' => 'compliance_officer', 'name' => 'Compliance Officer', 'department' => 'Risk & Control', 'is_system' => true],
        ['slug' => 'settlement_officer', 'name' => 'Settlement Officer', 'department' => 'Finance', 'is_system' => true],
        ['slug' => 'finance_treasury', 'name' => 'Finance / Treasury', 'department' => 'Finance', 'is_system' => true],
    ],

    /** Role slug => default landing path segment for backoffice SPA */
    'home_paths' => [
        'super_admin' => 'admin',
        'agent_manager' => 'agents',
        'aml_analyst' => 'aml',
        'compliance_officer' => 'kyc',
        'customer_support' => 'support',
        'kyc_officer' => 'kyc',
        'operations_lead' => 'operations',
        'settlement_officer' => 'settlement',
        'finance_treasury' => 'treasury',
    ],

];
